### ISSUE TITLE
DEV2-00 User gets assigned task list

### ISSUE THREAD

**Issue by martinskruze** [rubybattle/rubybattle.com#30]
### Prerequisites:
1. Working system
2. Campaign is switched to lobby mode

### Description:
- [ ] When user logins the system he/she sees other users waiting for game
- [ ] he/she is authomatically assigned 90 questions (30 easy/30 average/30 hard questions) 
- [ ] the questions must not be ones the user is author of or graded
