### ISSUE TITLE
Talk through user stories

### ISSUE THREAD

**Issue by martinskruze** [rubybattle/rubybattle.com#35]
- [ ] [DEV1-00 Basic campaign structure](https://github.com/rubybattle/rubybattle.com/issues/27)
- [ ] [DEV1-01 User can register and login to system](https://github.com/rubybattle/rubybattle.com/issues/15)
- [ ] [DEV1-02 User CRUD his/her questions with answers](https://github.com/rubybattle/rubybattle.com/issues/16)
- [ ] [DEV1-03 User gets assigned other questions for gradation/check](https://github.com/rubybattle/rubybattle.com/issues/17)
- [ ] [DEV1-04 User can comment and grade assigned questions](https://github.com/rubybattle/rubybattle.com/issues/18)
- [ ] [DEV1-05 User gets notified about gradation or request for update and can comment back](https://github.com/rubybattle/rubybattle.com/issues/19)
- [ ] [DEV1-A01 Administrator can login](https://github.com/rubybattle/rubybattle.com/issues/21)
- [ ] [DEV1-A02 Administrator can CRUD questions with answers](https://github.com/rubybattle/rubybattle.com/issues/22)
- [ ] [DEV1-A03 Administrator can see progress of gradation and evaluation process](https://github.com/rubybattle/rubybattle.com/issues/23)
- [ ] [DEV1-A04 Administrator can CRUD of campaign structure](https://github.com/rubybattle/rubybattle.com/issues/24)
- [ ] [DEV1-A05 Administrator can CRUD administrators](https://github.com/rubybattle/rubybattle.com/issues/25)
- [ ] [DEV1-A06 Administrator can CRUD users](https://github.com/rubybattle/rubybattle.com/issues/26)
- [ ] [DEV2-00 User gets assigned task list](https://github.com/rubybattle/rubybattle.com/issues/30)
- [ ] [DEV2-01 User can play the game (game playing)](https://github.com/rubybattle/rubybattle.com/issues/31)
- [ ] [DEV2-03 Watcher can see gameboard (game progress)](https://github.com/rubybattle/rubybattle.com/issues/33)
- [ ] [DEV2-04 Campaign closes after game is finished (game finish and results calculation)](https://github.com/rubybattle/rubybattle.com/issues/32)
- [ ] [DEV2-05 Watcher and user sees the results](https://github.com/rubybattle/rubybattle.com/issues/34)
